server:
  port: 7001

eureka:
  instance:
    #eureka服务端的实例名称(没有映射应该就是ip地址)
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false

    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #e.g. @Value("${test.id}")赋值
      #访问Eureka后台直接地址+端口
      #单机自己指向自己  defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群需要指向除了自己之外的所有server
      defaultZone: http://euraka7002.com:7002/eureka